"""Unit tests for ami.dataops.report.manifest (JCS + HMAC)."""

from __future__ import annotations

import hashlib
import hmac
import json
from pathlib import Path

import pytest

from ami.dataops.report.manifest import (
    SCHEMA_VERSION,
    ManifestFileEntry,
    SenderManifest,
    build_manifest,
    canonical_manifest_bytes,
    sign_manifest,
    verify_signature,
)

SHARED_SECRET = "s3cret"
UUID_STRING_LENGTH = 36
UUIDV7_VERSION_POSITION = 14
FIXED_BUNDLE_ID = "019237d0-2c41-71a5-9f7e-bd6a10b53c07"
FIXED_SENT_AT = "2026-04-19T08:12:00Z"


class TestBuildManifest:
    def test_minimal_happy_path(self, tmp_path: Path) -> None:
        (tmp_path / "a.log").write_text("alpha\n")
        (tmp_path / "nested").mkdir()
        (tmp_path / "nested" / "b.log").write_text("beta\n")
        manifest = build_manifest(
            sender_id="alpha",
            source_root=tmp_path,
            files=[tmp_path / "a.log", tmp_path / "nested" / "b.log"],
            bundle_id=FIXED_BUNDLE_ID,
            sent_at=FIXED_SENT_AT,
        )
        assert manifest.sender_id == "alpha"
        assert manifest.schema_version == SCHEMA_VERSION
        assert manifest.bundle_id == FIXED_BUNDLE_ID
        paths = [entry.relative_path for entry in manifest.files]
        assert paths == ["a.log", "nested/b.log"]
        for entry in manifest.files:
            absolute = tmp_path / entry.relative_path
            assert entry.sha256 == hashlib.sha256(absolute.read_bytes()).hexdigest()

    def test_autogenerated_bundle_id_is_uuidv7(self, tmp_path: Path) -> None:
        (tmp_path / "a.log").write_text("x\n")
        manifest = build_manifest(
            sender_id="alpha",
            source_root=tmp_path,
            files=[tmp_path / "a.log"],
        )
        assert len(manifest.bundle_id) == UUID_STRING_LENGTH
        assert manifest.bundle_id[UUIDV7_VERSION_POSITION] == "7"

    def test_file_outside_source_root_rejected(self, tmp_path: Path) -> None:
        (tmp_path / "inside.log").write_text("ok\n")
        outside = tmp_path.parent / "outside.log"
        outside.write_text("bad\n")
        with pytest.raises(ValueError, match="not under source_root"):
            build_manifest(
                sender_id="alpha",
                source_root=tmp_path,
                files=[outside],
            )
        outside.unlink()

    def test_missing_file_raises(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            build_manifest(
                sender_id="alpha",
                source_root=tmp_path,
                files=[tmp_path / "no-such.log"],
            )


class TestCanonicalBytes:
    def _manifest(self) -> SenderManifest:
        return SenderManifest(
            schema_version=1,
            sender_id="alpha",
            sent_at=FIXED_SENT_AT,
            bundle_id=FIXED_BUNDLE_ID,
            source_root="/tmp/src",
            files=[
                ManifestFileEntry(
                    relative_path="a.log",
                    sha256="a" * 64,
                    size_bytes=1,
                    mtime="2026-04-19T08:11:04Z",
                )
            ],
        )

    def test_bytes_end_with_single_lf(self) -> None:
        payload = canonical_manifest_bytes(self._manifest())
        assert payload.endswith(b"\n")
        assert not payload.endswith(b"\n\n")

    def test_bytes_are_deterministic(self) -> None:
        a = canonical_manifest_bytes(self._manifest())
        b = canonical_manifest_bytes(self._manifest())
        assert a == b

    def test_bytes_parse_as_jcs_sorted(self) -> None:
        payload = canonical_manifest_bytes(self._manifest())
        as_text = payload.decode("utf-8").rstrip("\n")
        parsed = json.loads(as_text)
        expected_keys = [
            "bundle_id",
            "files",
            "schema_version",
            "sender_id",
            "sent_at",
            "source_root",
        ]
        assert list(parsed.keys()) == expected_keys


class TestSigning:
    def test_sign_format(self) -> None:
        signature = sign_manifest(b"payload", SHARED_SECRET)
        assert signature.startswith("sha256=")
        hex_part = signature.removeprefix("sha256=")
        expected = hmac.new(
            SHARED_SECRET.encode("utf-8"), b"payload", hashlib.sha256
        ).hexdigest()
        assert hex_part == expected

    def test_verify_matches_sign(self) -> None:
        sig = sign_manifest(b"payload", SHARED_SECRET)
        assert verify_signature(b"payload", sig, SHARED_SECRET)

    def test_verify_rejects_bad_secret(self) -> None:
        sig = sign_manifest(b"payload", SHARED_SECRET)
        assert not verify_signature(b"payload", sig, "wrong-secret")

    def test_verify_rejects_tampered_payload(self) -> None:
        sig = sign_manifest(b"payload", SHARED_SECRET)
        assert not verify_signature(b"payload-tampered", sig, SHARED_SECRET)

    def test_verify_rejects_bad_scheme(self) -> None:
        assert not verify_signature(b"payload", "md5=ab", SHARED_SECRET)
